### ISSUE TITLE
Option to choose different editor

### ISSUE THREAD

**Issue by dogskool** [johnjones4/Standard-Notes-Clipper#25] opened 2020-10-18 17:51 UTC
When I clip from a web page, I have the choice to choose a different editor, but only the 'Plain Editor' is visible. Is there a way to get my other choices? (in both Firefox and Chrome)

**Comment by johnjones4** [comment] 2020-10-25 12:00
Hi @dogskool. Which other editors do you have enabled in your account?

**Comment by dogskool** [comment] 2020-10-25 16:02
Plain Editor, Bold Editor, Code Editor, Markdown Basic, Markdown Math, Markdown Pro, Plus Editor, Task Editor and Vim Editor. Almost all of them. 
![Screen Shot 2020-10-25 at 9 01 50 AM](https://user-images.githubusercontent.com/1085258/97112307-cb84f980-16a0-11eb-830e-7bff69b6abf9.png)

**Comment by ackstorm23** [comment] 2020-11-10 04:43
I have the same problem.  No editor choices when clipping.

**Comment by DonCorleone1988** [comment] 2020-12-13 17:46
I can concur that this is happening to me as well. I have almost all of the editors installed and the only option I have is the plain editor when clipping.

**Comment by johnjones4** [comment] 2020-12-21 16:12
Sorry for the delay here! The issue is fixed and will be in the next release. Stay tuned

**Comment by johnjones4** [comment] 2020-12-21 17:44
I believe this has been resolved in https://github.com/johnjones4/Standard-Notes-Clipper/releases/tag/1.7.1. Can someone please confirm for me?

**Comment by JaspalSuri** [comment] 2020-12-27 10:26
Hi @johnjones4,

Thanks for adding this feature! I was able to confirm that this worked in two tests with different editors.

**Closed as completed** 2020-12-27 12:27 UTC
